# Multilayer perceptron using backpropagation algorithm

In [1]:
import numpy as np

In [2]:
## initialize variable

def init(li, lh, lo):
    w1 = np.random.uniform(0,1,(li,lh))    #(input, hidden)
    w2 = np.random.uniform(0,1,(lh,lo))    #(hidden, output)
    th1 = np.random.uniform(0,1,(lh,1))    #(hidden, 1)
    th2 = np.random.uniform(0,1,(lo,1))    #(output, 1)
    
    k1 = 0.5
    k2 = 0.6
    
    n = 1<<li      #(2^li)
    lim = n//lo    #number in one class
    
    train_x = np.zeros((n,li))   # (2^input, input)
    train_y = np.zeros((n,lo))   # (2^input, output)
    
    for i in range(0,n):
        for j in range(0,li):
            if(i&(1<<j)):
                train_x[i][j]=1
    for i in range(0,n):
        train_y[i,i//lim]= 1
    
    return n, train_x, train_y, w1, w2, th1, th2, k1, k2

In [3]:
def sigmoid(k, activ):
    t = 1 + np.exp(-1*k*activ)
    return (1/t)

In [4]:
def layer(x,w,th,k):
    net = np.matmul(x,w)
    activ = net + np.transpose(th)
    out = sigmoid(k,activ)
    return out

In [5]:
def calculate_tot_error(train_x, train_y, w1, w2, th1, th2, k1, k2):
    oj = layer(train_x, w1, th1, k1)
    ok = layer(oj, w2, th2, k1)
    t = np.sum((train_y - ok)**2)*0.5
    return t

In [22]:
def learn_multilayer(n, li, lh, lo, train_x, train_y, w1, w2, th1, th2, k1, k2):
    """
    parameter:
        train_x = inputs , shape of (n,li)
        train_y = desired output , shape of (n,lo)
        w1 = weight of input layer, shape of (li,lh)
        w2 = weight of hidden layer, shape of (lh,lo)
        th1 = threshold of input layer, shape of (lh,1)
        th2 = threshole of hidden layer , shape of (lo,1)
        k1, k2  = 
    return:
        w1, w2, th1, th2
    """
    learning_rate1 = 0.01
    learning_rate2 = 0.01
    cnt=0
    
    while(True):
        for i in range (0,n):
            
            Oj = layer(np.reshape(train_x[i,:],(1,li)), w1, th1, k1)
            
            Ok = layer(Oj, w2, th2, k2)
            
            
            err = train_y[i,:] - Ok      # (1,lo)
            
            
            del_w2 = np.matmul(np.transpose(Oj),learning_rate2*k2*err*Ok*(1-Ok))
            w2 = w2 + del_w2

            del_th2 = learning_rate2*k2*err*Ok*(1-Ok)
            th2 = th2 + np.transpose(del_th2)


            s = np.matmul(err, np.transpose(w2))
            s = learning_rate1*k1*Oj*(1-Oj)*s

            del_w1 = np.matmul(np.transpose(np.reshape(train_x[i,:],(1,li))), s)
            w1 = w1 + del_w1

            del_th1 = np.transpose(s)
            th1 = th1 + del_th1
            
        totalError = calculate_tot_error(train_x, train_y, w1, w2, th1, th2, k1, k2)
        cnt+=1
        
        if(cnt%1000 ==0 ):
            print(totalError)
        if(totalError<0.01 or cnt==1000000):
            break
                
                
    return w1, w2, th1, th2

In [23]:
n, train_x, train_y, w1, w2, th1, th2, k1, k2 = init(6,3,4)

print(train_x)
print(train_y)
print(w1)
print(w2)
print(th1)
print(th2)

w1, w2, th1, th2 = learn_multilayer(n, 6, 3, 4, train_x, train_y, w1, w2, th1, th2, k1, k2)

print('-------')
print(w1)
print(w2)
print(th1)
print(th2)

[[0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [1. 0. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0. 0.]
 [1. 1. 0. 1. 0. 0.]
 [0. 0. 1. 1. 0. 0.]
 [1. 0. 1. 1. 0. 0.]
 [0. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0.]
 [1. 1. 0. 0. 1. 0.]
 [0. 0. 1. 0. 1. 0.]
 [1. 0. 1. 0. 1. 0.]
 [0. 1. 1. 0. 1. 0.]
 [1. 1. 1. 0. 1. 0.]
 [0. 0. 0. 1. 1. 0.]
 [1. 0. 0. 1. 1. 0.]
 [0. 1. 0. 1. 1. 0.]
 [1. 1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [0. 1. 0. 0. 0. 1.]
 [1. 1. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 0. 1.]
 [0. 1. 1. 0. 0. 1.]
 [1. 1. 1. 0. 0. 1.]
 [0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0. 1.]
 [0. 1. 0. 1. 0. 1.]
 [1. 1. 0. 1. 0. 1.]
 [0. 0. 1. 1. 0. 1.]
 [1. 0. 1. 1. 0. 1.]
 [0. 1. 1. 1. 0. 1.]
 [1. 1. 1. 1.

0.03618693212039135
0.03607665876160483
0.035967122013098776
0.03585831429976445
0.03575022815149057
0.03564285620132404
0.03553619118369039
0.03543022593262758
0.03532495338007694
0.03522036655422516
0.03511645857783316
0.03501322266661755
0.034910652127685876
0.034808740357988505
0.034707480842827654
0.0346068671543293
0.03450689294999508
0.03440755197130983
0.03430883804234383
0.03421074506832303
0.034113267034351066
0.03401639800409232
0.033920132118446605
0.033824463594293495
0.033729386723299976
0.03363489587065729
0.03354098547387753
0.03344765004170161
0.033354884152885664
0.0332626824550742
0.033171039663789155
0.03307995056122594
0.03298940999527204
0.032899412878493184
0.032809954186998946
0.03272102895958792
0.0326326322966551
0.03254475935926141
0.03245740536826207
0.032370565603227486
0.03228423540170193
0.03219841015817806
0.03211308532330888
0.03202825640300794
0.031943918957587386
0.031860068601008866
0.031776700999939574
0.03169381187313134
0.03161139699041743
0.03152

0.017069752653933984
0.017048605446179206
0.017027515812077086
0.01700648350975289
0.01698550829870961
0.016964589939795008
0.016943728195191618
0.016922922828428562
0.01690217360437763
0.01688148028928357
0.016860842650633177
0.0168402604572006
0.016819733479131557
0.016799261487855335
0.016778844256072945
0.016758481557705544
0.01673817316795605
0.016717918863293154
0.016697718421449737
0.016677571621390337
0.016657478243245
0.01663743806837975
0.01661745087940517
0.016597516460148773
0.01657763459557916
0.016557805071856842
0.016538027676358605
0.0165183021975733
0.016498628425175105
0.016479006149973753
0.01645943516393853
0.016439915260154793
0.016420446232858633
0.016401027877414855
0.01638165999029284
0.016362342369035884
0.016343074812314874
0.016323857119881102
0.01630468909254964
0.016285570532265054
0.016266501241997657
0.016247481025767677
0.016228509688641576
0.016209587036763416
0.016190712877337546
0.016171887018575797
0.016153109269691504
0.016134379440915517
0.01611569

In [24]:
Oj = layer(np.reshape(train_x[62,:], (1,6)), w1, th1, k1)
Ok = layer(Oj, w2, th2, k2)
print(Ok)

[[1.69134325e-05 4.20187819e-03 4.19941898e-03 9.93004820e-01]]
